name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4  # Shallow clone is enabled by default

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
          uv pip install --system ruff pytest

      - name: Lint with ruff
        run: |
          ruff check . || true

      - name: Run tests with pytest
        run: |
          pytest

      - name: Test Total War Attila main.py
        run: |
          python -m games.tw.attila.main
